name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: |
          gem install bundler:2.5.6
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build  # Modify this command as needed for your build process

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Adjust this to the directory where your built site resides

